export type ProjectImage = {
  src: string;
  alt: string;
  label: string;
  description: string;
  group: string;
  theme: "light" | "dark";
  emphasis: "hero" | "feature" | "supporting";
  device?: "desktop" | "mobile";
  width: number;
  height: number;
};

export type ProjectPreviewImage = Pick<ProjectImage, "src" | "alt" | "label">;

export type Project = {
  slug: string;
  title: string;
  eyebrow: string;
  summary: string;
  challenge: string;
  solution: string;
  achievements: string[];
  tech: string[];
  link?: string;
  confidential?: boolean;
  images?: ProjectImage[];
  lightPreviewImages?: ProjectPreviewImage[];
  previewLabel?: string;
  previewStatus?: string;
  previewVariant?: "trading" | "investor" | "banking" | "messaging" | "workspace";
  businessOverview?: string;
  technicalOverview?: string;
  engineeringChallenges?: string[];
  engineeringHeading?: string;
  engineeringIntro?: string;
  technologyHeading?: string;
  stackGroups?: { label: string; items: string[] }[];
  gallery?: {
    eyebrow: string;
    title: string;
    intro: string;
    capabilities: string[];
    groups: { name: string; description: string }[];
  };
  accent: "teal" | "coral" | "amber";
};

const oms = (file: string) => `/images/projects/oms/${file}`;
const atom = (file: string) => `/images/projects/attom/${file}`;
const pwa = (file: string) => `/images/projects/pwa/${file}`;
const sms = (file: string) => `/images/projects/sms/${file}`;
const workDesk = (file: string) => `/images/projects/wd/${file}`;

export const profile = {
  name: "Fatemeh Kashfi",
  role: "Senior Frontend Engineer",
  location: "Tehran, Iran",
  email: "kashfi.sf@gmail.com",
  phone: "+98 919 649 5033",
  intro:
    "I architect high-performance interfaces for complex, mission-critical platforms—spanning real-time data environments, enterprise workflows, and scalable SaaS products.",
  about:
    "Senior Frontend Engineer with experience building scalable React and Next.js applications across fintech, capital markets, and oil, gas, and petrochemical operations. I turn dense workflows into clear product experiences, pairing strong TypeScript architecture with thoughtful interaction design, testing, and performance engineering.",
  links: {
    github: "https://github.com/sf-kashfi/",
    linkedin: "https://www.linkedin.com/in/fateme-kashfi/",
    telegram: "https://t.me/sfkashfi",
  },
};

export const metrics = [
  { value: "16+", label: "Enterprise Projects Shipped" },
  { value: "30%", label: "OMS UI performance gain" },
  { value: "10+", label: "Teams Collaborated" },
  { value: "12+", label: "domain modules delivered" },
];

export const experience = [
  {
    period: "Dec 2025 — Present",
    role: "Senior Frontend Developer",
    company: "Hirbod Niroo",
    domain: "Oil, Gas & Petrochemical",
    summary:
      "Leading the frontend architecture of a unified enterprise workspace for operational teams.",
    highlights: [
      "Architected a window management system hosting 30+ draggable and resizable applications with portal-aware stacking and container-query layouts.",
      "Modularized a legacy work desk into 12+ domain-scoped TypeScript modules with typed services and React Query data hooks.",
      "Built conflict-aware meeting scheduling, calendar timelines, minutes capture, Excel export, and Playwright lifecycle coverage.",
      "Delivered permission-aware Kanban workflows, nested file management, work logs, and analytics reporting.",
    ],
  },
  {
    period: "Dec 2024 — Dec 2025",
    role: "Frontend Developer",
    company: "OmidBank",
    domain: "Fintech · Bank Sepah",
    summary:
      "Built secure, responsive banking experiences across PWA, Android web views, and administration tools.",
    highlights: [
      "Delivered banking flows for transfers, cheques, loans, guarantees, cards, and wallets using React Query and Material UI.",
      "Implemented Axios encryption and decryption interceptors to strengthen API data handling.",
      "Built a ref-counted SSE client with topic multiplexing, token-aware reconnect, and automatic query invalidation.",
      "Maintained Vue.js administration features and led the migration direction toward React.",
    ],
  },
  {
    period: "Sep 2021 — Dec 2024",
    role: "Frontend Developer",
    company: "Datxsoft",
    domain: "Capital Markets · Pasargad Financial Group",
    summary:
      "Developed data-intensive trading and investment products used in high-traffic financial operations.",
    highlights: [
      "Improved order-management UI performance by 30% with React, TypeScript, and Redux.",
      "Integrated Material UI and AG Grid to streamline operational workflows, contributing to a 20% task-efficiency gain.",
      "Reduced load time by 15% while maintaining and refactoring ExtJS and AngularJS systems.",
      "Delivered a concurrent SharePoint and React smart-office project that optimized content workflows by 25%.",
    ],
  },
];

const projectCatalog: Project[] = [
  {
    slug: "omid-bank",
    title: "Omid Bank",
    eyebrow: "Mobile banking · RTL PWA",
    summary:
      "A unified mobile banking PWA connecting wallets, transfers, payments, deposits, cards, loans, investments, and civic services in one production-grade RTL experience.",
    challenge:
      "Bring a broad banking architecture into a trustworthy mobile interface while protecting sensitive browser data, coordinating long financial workflows, and staying responsive on constrained networks.",
    solution:
      "A lazy-loaded React PWA with layered authorization, encrypted client data, domain-focused state coordinators, validated financial forms, and virtualized mobile collections.",
    achievements: [
      "12+ connected banking and lifestyle service families",
      "Layered consumer and bank-service authorization",
      "Secure PWA and Android WebView delivery",
      "Responsive data-heavy financial workflows",
    ],
    tech: ["React", "React Router", "TanStack Query", "Material UI", "React Hook Form", "Axios", "Web Crypto", "Framer Motion"],
    link: "https://omidbank.ir/app/",
    previewLabel: "OMID BANK / MOBILE SERVICE PLATFORM",
    previewStatus: "RTL · SECURE PWA",
    previewVariant: "banking",
    businessOverview:
      "Omid Bank helps customers complete everyday banking and adjacent daily tasks without visiting a branch. A service-led home connects wallet operations, card-to-card transfers, bill inquiry and payment, SIM charge and internet packages, mutual funds, and a dedicated banking area for deposits, cards, loans, and onboarding. Civic tools extend the same mobile experience to traffic fines, license status, negative points, and passport inquiries. Mobile OTP provides fast entry, while a second user-management login protects deeper bank workflows and keeps balances, statements, installments, and requests visible in one coherent RTL product.",
    technicalOverview:
      "The React application is organized around a large lazy-loaded route catalog spanning independent financial domains. TanStack Query manages server state, while focused Context providers coordinate authentication, wallet, transfer, loan, and modal workflows. Material UI and Emotion provide RTL-aware layouts; React Hook Form and Yup structure validation; and Axios V1/V2 facades isolate backend contracts. Browser sessions use Web Crypto AES-GCM, selected request bodies use AES with RSA-wrapped keys, and guarded route layers separate general access from advanced banking services. Virtualized lists, infinite queries, Suspense fallbacks, WebView-aware layouts, Jalali dates, and i18next keep the product responsive across mobile web and embedded Android contexts.",
    engineeringChallenges: [
      "Secure browser-side banking data: AES-GCM protects session cookies, while selected payloads use AES encryption with RSA-wrapped keys before transport.",
      "Coordinated financial journeys: focused Context handlers connect drawers, dialogs, confirmations, and shared state without pushing every concern through page props.",
      "Layered authorization: separate guards validate primary and user-management tokens so lightweight consumer services and deeper bank workflows have distinct access boundaries.",
      "Large route and data surfaces: lazy routes, Suspense fallbacks, virtualized lists, and infinite-query patterns protect startup and scrolling performance on mobile networks.",
    ],
    stackGroups: [
      { label: "Core", items: ["React", "React Router", "Lazy routes", "Suspense"] },
      { label: "State", items: ["TanStack Query", "React Context", "Infinite queries"] },
      { label: "Forms & API", items: ["React Hook Form", "Yup", "Axios V1/V2", "Custom interceptors"] },
      { label: "UI & RTL", items: ["Material UI", "Emotion", "stylis-plugin-rtl", "i18next", "Jalali dates"] },
      { label: "Security", items: ["Web Crypto AES-GCM", "node-forge RSA", "Layered route guards"] },
      { label: "Motion & media", items: ["Framer Motion", "Swiper", "react-virtuoso", "QR scan/share", "html2canvas"] },
    ],
    gallery: {
      eyebrow: "Mobile product system",
      title: "A bank, wallet, and daily-service layer in one hand.",
      intro:
        "The walkthrough prioritizes screens that reveal the product's breadth: a service-led home, protected banking tools, transaction flows, long-form loan states, and civic inquiries, all designed as readable Persian RTL mobile experiences.",
      capabilities: ["Service home", "Wallet", "Transfers", "Deposits & cards", "Loans", "Civic inquiries", "Secure access"],
      groups: [
        { name: "Everyday banking", description: "Service discovery, wallet movement, card transfers, and transaction confirmation stay focused and thumb-friendly." },
        { name: "Deposits & cards", description: "A protected banking layer connects deposit visibility, card lifecycle operations, credentials, and service activation." },
        { name: "Loans & installments", description: "Lookup, saved facilities, and installment payment states make longer credit workflows understandable on a narrow screen." },
        { name: "Civic inquiries", description: "Vehicle records and traffic-fine workflows extend the product beyond banking without changing its core mobile interaction language." },
        { name: "Access & profile", description: "Secondary authentication and customer details support the deeper permissions and identity requirements behind bank services." },
      ],
    },
    images: [
      {
        src: pwa("service-home.png"),
        alt: "Omid Bank Persian RTL mobile service home with bill, internet, charge, transfer, insurance, health, travel, and financial-service shortcuts",
        label: "Service home",
        description: "A broad service catalog gives everyday banking and lifestyle tasks a clear, scannable mobile entry point.",
        group: "Everyday banking",
        theme: "light",
        emphasis: "hero",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("card-services-hub.png"),
        alt: "Omid Bank Persian RTL card-services dashboard with card issuance, card-to-card transfer, password services, and recent transactions",
        label: "Card services hub",
        description: "Card issuance, transfers, credential tools, cheque payment, and recent activity share one protected banking surface.",
        group: "Deposits & cards",
        theme: "light",
        emphasis: "feature",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("civic-services-hub.png"),
        alt: "Omid Bank Persian RTL police-services dashboard with traffic fines, active plates, license inquiry, negative points, and passport inquiry",
        label: "Civic services",
        description: "Police and identity inquiries extend the same mobile product into high-frequency civic tasks.",
        group: "Civic inquiries",
        theme: "light",
        emphasis: "feature",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("wallet-account-transfer.png"),
        alt: "Omid Bank Persian RTL wallet transfer form with digital deposit card, destination tabs, amount, and transfer descriptions",
        label: "Wallet transfer",
        description: "A detailed account-transfer form keeps source balance, destination choice, amount, and descriptions visible in one flow.",
        group: "Everyday banking",
        theme: "light",
        emphasis: "feature",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("card-to-card-transfer.png"),
        alt: "Omid Bank Persian RTL card-to-card transfer form with source card, destination card, amount, and OTP request",
        label: "Card-to-card transfer",
        description: "Source credentials, destination details, amount, and dynamic-password retrieval form a compact validated journey.",
        group: "Everyday banking",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("card-transfer-receipt.png"),
        alt: "Omid Bank Persian RTL successful card-to-card transaction receipt with amount, tracking code, timestamp, and share actions",
        label: "Transfer receipt",
        description: "A receipt-like confirmation makes the amount, reference, service, and sharing actions easy to verify after payment.",
        group: "Everyday banking",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("deposit-services.png"),
        alt: "Omid Bank Persian RTL deposit-services dashboard with account card, IBAN conversion, statement, transfer, customer information, and SMS activation",
        label: "Deposit services",
        description: "A dedicated deposit workspace connects account identifiers, statements, transfers, profile data, and SMS activation.",
        group: "Deposits & cards",
        theme: "light",
        emphasis: "feature",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("card-operations.png"),
        alt: "Omid Bank Persian RTL card-operations list for issuance, replacement, cancellation, and blocking",
        label: "Card lifecycle",
        description: "Card issuance, replacement, cancellation, and blocking are organized as explicit lifecycle actions.",
        group: "Deposits & cards",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("card-password-services.png"),
        alt: "Omid Bank Persian RTL card-password services screen for first password, second password, and dynamic password",
        label: "Card credentials",
        description: "Static and dynamic credential tools are separated into clear actions with contextual account information.",
        group: "Deposits & cards",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("deposit-sms-activation.png"),
        alt: "Omid Bank Persian RTL deposit SMS activation screen with account summary, mobile number, fee, and confirmation",
        label: "SMS activation",
        description: "Fee, account, phone number, and activation window remain visible before a customer confirms the service request.",
        group: "Deposits & cards",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("loan-installment-payment.png"),
        alt: "Omid Bank Persian RTL installment payment form for another borrower with loan owner, account selection, and payment amount",
        label: "Installment payment",
        description: "Borrower context, source account, and payment amount are sequenced into a focused installment journey.",
        group: "Loans & installments",
        theme: "light",
        emphasis: "feature",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("loan-installment-lookup.png"),
        alt: "Omid Bank Persian RTL loan dashboard with saved facilities and an installment-number inquiry sheet",
        label: "Facility lookup",
        description: "A bottom-sheet lookup keeps saved facilities in context while requesting a new installment number.",
        group: "Loans & installments",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("saved-loan-number.png"),
        alt: "Omid Bank Persian RTL save-facility sheet over a successful loan transaction report",
        label: "Saved facility",
        description: "Customers can name and retain facility numbers after payment, reducing friction across repeat installment tasks.",
        group: "Loans & installments",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("vehicle-plate-list.png"),
        alt: "Omid Bank Persian RTL vehicle-fine screen listing saved Iranian license plates with edit and inquiry actions",
        label: "Saved vehicle plates",
        description: "Multiple plate types, edit controls, and a direct inquiry action support households with several vehicles.",
        group: "Civic inquiries",
        theme: "light",
        emphasis: "feature",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("traffic-fines-detail.png"),
        alt: "Omid Bank Persian RTL vehicle-fine details with plate, total status, individual violations, image links, and payment actions",
        label: "Traffic fine details",
        description: "Fine totals, dates, locations, evidence, and individual or bulk payment actions remain legible in a long mobile list.",
        group: "Civic inquiries",
        theme: "light",
        emphasis: "feature",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("paid-fine-status.png"),
        alt: "Omid Bank Persian RTL paid vehicle-fine status showing a saved plate, inquiry date, and settled confirmation",
        label: "Settled fine status",
        description: "A calm resolved state confirms that a saved vehicle has no outstanding traffic fines.",
        group: "Civic inquiries",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("secure-banking-login.png"),
        alt: "Omid Bank Persian RTL secondary banking login with username, password, recovery link, and secure-access illustration",
        label: "Layered bank access",
        description: "A second authenticated boundary unlocks protected deposit, card, facility, and customer-management workflows.",
        group: "Access & profile",
        theme: "light",
        emphasis: "feature",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: pwa("customer-profile.png"),
        alt: "Omid Bank Persian RTL customer profile form with personal details and province and city selection",
        label: "Customer profile",
        description: "Identity details and regional information use familiar mobile controls within the shared product shell.",
        group: "Access & profile",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
    ],
    accent: "coral",
  },
  {
    slug: "order-management",
    title: "OMS",
    eyebrow: "Financial trading platform",
    summary:
      "A comprehensive Order Management System built with React to streamline trading across financial instruments—from market watch and execution to portfolios, accounting, OTC workflows, and analysis.",
    challenge:
      "Unify large, rapidly changing market datasets and high-stakes trading actions in an interface that remains fast, legible, and dependable for expert operators.",
    solution:
      "A performance-focused React and TypeScript frontend with normalized Redux Toolkit state, saga-driven workflows, AG Grid data surfaces, validated forms, and domain-specific visualizations including portfolio treemaps.",
    achievements: [
      "30% UI performance improvement",
      "20% task-efficiency increase",
      "Multi-instrument trading workflows",
      "Real-time portfolio visualization",
    ],
    tech: [
      "React",
      "TypeScript",
      "Redux",
      "Redux Toolkit",
      "Redux Saga",
      "Material UI",
      "AG Grid",
      "React Hook Form",
      "Yup",
    ],
    lightPreviewImages: [
      {
        src: oms("technical-analysis-light.png"),
        alt: "OMS light-theme technical analysis workspace with candlestick chart, volume, and drawing tools",
        label: "Technical analysis",
      },
      {
        src: oms("market-treemap-light.png"),
        alt: "OMS light-theme market treemap showing sector and instrument performance with proportional tiles",
        label: "Market treemap",
      },
      {
        src: oms("broker-order-entry-light.png"),
        alt: "OMS light-theme order entry workflow with broker selection, market watch, and order history",
        label: "Order entry",
      },
    ],
    images: [
      {
        src: oms("market-overview.png"),
        alt: "OMS market overview dashboard with index chart, capital activity, and high-volume trading tables",
        label: "Market overview",
        description: "A consolidated view of market movement, capital activity, high-volume symbols, and live index performance.",
        group: "Market intelligence",
        theme: "dark",
        emphasis: "hero",
        width: 1024,
        height: 512,
      },
      {
        src: oms("market-treemap.png"),
        alt: "OMS market treemap visualizing portfolio and sector performance with proportional tiles",
        label: "Market treemap",
        description: "A proportional heat map that makes sector breadth, winners, and laggards immediately scannable.",
        group: "Market intelligence",
        theme: "dark",
        emphasis: "feature",
        width: 1024,
        height: 512,
      },
      {
        src: oms("technical-analysis.png"),
        alt: "OMS technical analysis workspace showing a detailed candlestick chart and trading volume",
        label: "Technical analysis",
        description: "A focused charting workspace with candlesticks, volume, drawing tools, and market context.",
        group: "Market intelligence",
        theme: "dark",
        emphasis: "feature",
        width: 1024,
        height: 487,
      },
      {
        src: oms("symbol-dashboard.png"),
        alt: "OMS symbol dashboard combining trade flow, valuation, market depth, and financial indicators",
        label: "Symbol dashboard",
        description: "Dense symbol-level intelligence organized into clear analytical modules and comparison panels.",
        group: "Market intelligence",
        theme: "dark",
        emphasis: "feature",
        width: 1024,
        height: 488,
      },
      {
        src: oms("symbol-analysis.png"),
        alt: "OMS symbol analysis screen with indicators, support and resistance levels, and market status",
        label: "Symbol analysis",
        description: "Technical indicators, price levels, and trend signals brought together for faster evaluation.",
        group: "Market intelligence",
        theme: "dark",
        emphasis: "supporting",
        width: 1024,
        height: 488,
      },
      {
        src: oms("market-depth.png"),
        alt: "OMS market depth table with bid and ask quantities across a large instrument watchlist",
        label: "Market depth",
        description: "A high-density depth surface designed for scanning bid, ask, volume, and price movement.",
        group: "Market intelligence",
        theme: "dark",
        emphasis: "supporting",
        width: 1024,
        height: 487,
      },
      {
        src: oms("market-watch.png"),
        alt: "OMS market watch with instrument sparklines, live prices, and bid and ask columns",
        label: "Market watch",
        description: "Live instruments, compact trend lines, price changes, and market actions in one operational view.",
        group: "Market intelligence",
        theme: "dark",
        emphasis: "supporting",
        width: 1024,
        height: 489,
      },
      {
        src: oms("legacy-market-overview-light.png"),
        alt: "OMS light-theme chronological order history with account balances and conditional order actions",
        label: "Order timeline",
        description: "A date-grouped order history that keeps balances, status, and conditional order actions close at hand.",
        group: "Trading operations",
        theme: "light",
        emphasis: "supporting",
        width: 1024,
        height: 512,
      },
      {
        src: oms("orders-market-watch.png"),
        alt: "OMS trading workspace with market watch, order book, and order management grids",
        label: "Orders & market watch",
        description: "A multi-panel workspace for monitoring instruments while managing active and historical orders.",
        group: "Trading operations",
        theme: "dark",
        emphasis: "feature",
        width: 1024,
        height: 512,
      },
      {
        src: oms("orders-and-trades.png"),
        alt: "OMS portfolio and order tracking workspace with holdings and active order grids",
        label: "Orders & trades",
        description: "Holdings and order state stay linked so operators can monitor positions while tracking every execution.",
        group: "Trading operations",
        theme: "dark",
        emphasis: "feature",
        width: 1024,
        height: 512,
      },
      {
        src: oms("order-ticket-light.png"),
        alt: "OMS light-theme order ticket over market watch and order history tables",
        label: "Order ticket",
        description: "A compact execution ticket keeps quantity, price, validity, and order-side controls close to market context.",
        group: "Trading operations",
        theme: "light",
        emphasis: "feature",
        width: 1024,
        height: 512,
      },
      {
        src: oms("broker-order-entry-light.png"),
        alt: "OMS light-theme order entry workflow with broker selection and order form",
        label: "Broker order entry",
        description: "Broker selection, account controls, and validated execution fields in a guided order workflow.",
        group: "Trading operations",
        theme: "light",
        emphasis: "supporting",
        width: 1024,
        height: 512,
      },
      {
        src: oms("order-amendment.png"),
        alt: "OMS initial offering and securities subscription request form over order tables",
        label: "Offering request",
        description: "Initial offering and subscription requests capture volume, price limits, and validation constraints in one form.",
        group: "Trading operations",
        theme: "dark",
        emphasis: "supporting",
        width: 1024,
        height: 512,
      },
      {
        src: oms("trading-calendar.png"),
        alt: "OMS monthly trading calendar with daily activity indicators and transaction volume summaries",
        label: "Trading calendar",
        description: "Monthly activity patterns and buy/sell distribution summarized for historical review.",
        group: "Trading operations",
        theme: "dark",
        emphasis: "supporting",
        width: 1024,
        height: 660,
      },
      {
        src: oms("modular-trading-workspace.png"),
        alt: "OMS modular trading workspace showing market watch, portfolio, and order management panels",
        label: "Modular workspace",
        description: "Independent data modules combine into a flexible operating surface for day-to-day trading.",
        group: "Trading operations",
        theme: "dark",
        emphasis: "supporting",
        width: 1024,
        height: 512,
      },
      {
        src: oms("otc-requests-light.png"),
        alt: "OMS light-theme over-the-counter request workflow with request and response tables",
        label: "OTC requests",
        description: "Request and response states for over-the-counter transactions presented in a focused workflow.",
        group: "Trading operations",
        theme: "light",
        emphasis: "supporting",
        width: 1024,
        height: 512,
      },
      {
        src: oms("portfolio-market-watch.png"),
        alt: "OMS portfolio allocation panel beside a comprehensive market watch table",
        label: "Portfolio allocation",
        description: "Portfolio distribution and market positions remain visible alongside a detailed instrument watchlist.",
        group: "Portfolio & access",
        theme: "dark",
        emphasis: "feature",
        width: 1024,
        height: 512,
      },
      {
        src: oms("portfolio-dashboard.png"),
        alt: "OMS portfolio dashboard with allocation chart, holdings table, and market watch",
        label: "Portfolio dashboard",
        description: "Allocation, holdings detail, and market context share one surface for faster portfolio decisions.",
        group: "Portfolio & access",
        theme: "dark",
        emphasis: "feature",
        width: 1024,
        height: 512,
      },
      {
        src: oms("portfolio-allocation-dashboard.png"),
        alt: "OMS portfolio allocation dashboard with donut chart, instrument table, and allocation tooltip",
        label: "Allocation detail",
        description: "Interactive allocation detail links portfolio composition to the underlying instrument data.",
        group: "Portfolio & access",
        theme: "dark",
        emphasis: "supporting",
        width: 1024,
        height: 512,
      },
      {
        src: oms("login.png"),
        alt: "Pasargad Trader OMS sign-in page with a laptop preview of the market dashboard",
        label: "Secure access",
        description: "The authenticated product entry point introduces the trading environment and account access.",
        group: "Portfolio & access",
        theme: "dark",
        emphasis: "supporting",
        width: 1024,
        height: 512,
      },
    ],
    link: "https://app.pasargadtrader.ir/",
    previewLabel: "OMS / LIVE TRADING ENVIRONMENT",
    previewStatus: "REAL-TIME",
    previewVariant: "trading",
    accent: "amber",
  },
  {
    slug: "atom-investor",
    title: "Atom Investor (InvestoPod)",
    eyebrow: "Capital markets · Investor platform",
    summary:
      "A digital investor gateway for Pasargad funds, connecting Sejam onboarding, portfolio visibility, unit issue and redemption, payment, and order tracking in a responsive RTL experience.",
    challenge:
      "Give investors a dependable self-service path through regulated identity checks, fund transactions, payment, and account servicing without relying on branch or offline processes.",
    solution:
      "A Vite and React SPA with typed domain contracts, Redux Toolkit and saga orchestration, centralized Axios services, and accessible MUI workflows designed for Persian RTL financial data.",
    achievements: [
      "Sejam-backed investor onboarding",
      "Issue, agreement, and payment orchestration",
      "Redemption against available fund units",
      "Filterable orders, revocation, and statements",
    ],
    tech: ["React", "TypeScript", "Redux Toolkit", "Redux Saga", "Vite", "MUI", "Axios", "MUI Data Grid"],
    previewLabel: "INVESTOPOD / INVESTOR GATEWAY",
    previewStatus: "RTL · PWA",
    previewVariant: "investor",
    businessOverview:
      "Atom Investor is the digital investor gateway for funds managed under the Pasargad capital-market services group. It enables investors to open access, complete regulatory identity steps, and place subscription (issue) and redemption requests without relying solely on branch or offline processes. Sejam-backed registration and login lead into portfolio holdings and fund NAV context, multi-step purchases with agreement acceptance and payment, redemption against available units, order tracking with filters and revocation where allowed, and account statement review. Profile tools also support Sejam data refresh and password management, keeping identity, payment, and portfolio data aligned throughout the investor journey.",
    technicalOverview:
      "The frontend is a Vite, React, and TypeScript SPA organized into pages, shared components, theme, and an application layer for models, API services, and state. Hash-based routing separates public authentication and landing routes from an authenticated sidebar shell. Redux Toolkit slices and redux-saga coordinate portfolio enrichment, paginated orders with per-document status, statements, fund catalog data, and draft issue creation followed by agreement retrieval. Centralized Axios wrappers attach session tokens, support multipart uploads, normalize API envelopes, and surface Persian toast feedback. MUI Data Grid, Jalali date pickers, multi-step wizards, typed DTOs, reusable forms, and light/dark Yekan themes support a maintainable RTL product as fund and order APIs evolve.",
    engineeringChallenges: [
      "Multi-step issue and payment branching: draft creation leads to agreement retrieval, then receipt upload or gateway payment while preserving request context across an external redirect.",
      "Order-list enrichment: each row combines document status, mapped fund identity, and cancellation eligibility before the Data Grid is ready to render.",
      "Sejam and fund-access gating: navigation blockers and contextual dialogs prevent investors from entering issue or redemption flows before eligibility checks pass.",
      "Clear UI and state boundaries: API models, saga side effects, Redux slices, and reusable view components stay separated as transaction workflows grow.",
    ],
    stackGroups: [
      { label: "Core", items: ["React", "TypeScript", "Vite", "React Router DOM (hash)"] },
      { label: "State", items: ["Redux", "Redux Toolkit", "Redux Saga", "React Context"] },
      { label: "Data & forms", items: ["Axios", "Controlled forms", "Custom ID/password validation", "MUI LoadingButton"] },
      { label: "UI & RTL", items: ["MUI", "MUI Lab", "Emotion", "Bootstrap", "iconsax-react", "MUI Icons", "React Toastify", "MUI Carousel"] },
      { label: "Tables & dates", items: ["MUI X Data Grid", "MUI X Charts", "MUI X Date Pickers", "date-fns-jalali"] },
      { label: "Tooling", items: ["ESLint", "TypeScript ESLint", "Vite React plugin"] },
    ],
    gallery: {
      eyebrow: "Investor journey",
      title: "From verified access to settled fund orders.",
      intro:
        "The product connects identity, portfolio context, transactions, and servicing in one Persian RTL journey. Desktop data surfaces and focused mobile steps keep the same financial state understandable at every point.",
      capabilities: ["Sejam access", "Portfolio", "Fund issue", "Payment", "Redemption", "Order tracking", "Statements"],
      groups: [
        { name: "Access & identity", description: "Authentication and Sejam verification establish trusted access before an investor can move money or manage fund units." },
        { name: "Portfolio overview", description: "Responsive dashboards connect holdings, NAV context, bank details, service hours, and the next available action." },
        { name: "Issue & payment", description: "Guided issue steps preserve fund and request context from amount entry through payment selection and confirmation." },
        { name: "Servicing & records", description: "Redemption, request status, statements, and filtered RTL grids keep account activity traceable after an order is placed." },
      ],
    },
    images: [
      {
        src: atom("Dashboard -1-28.jpg"),
        alt: "Atom Investor desktop dashboard in Persian showing fund NAV cards, investor holdings, bank accounts, service hours, and issue and redemption journeys",
        label: "Investor dashboard",
        description: "A complete investor overview links holdings, current NAVs, bank accounts, operating windows, and the two core fund journeys.",
        group: "Portfolio overview",
        theme: "light",
        emphasis: "hero",
        device: "desktop",
        width: 1440,
        height: 1024,
      },
      {
        src: atom("Investo PWA-39.png"),
        alt: "Atom Investor mobile dashboard in Persian with funds, holdings, NAV values, account information, and operating hours",
        label: "Mobile portfolio",
        description: "The extended mobile dashboard keeps fund access, holdings, NAV values, and service context available without compressing the RTL hierarchy.",
        group: "Portfolio overview",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 1024,
      },
      {
        src: atom("Investo PWA-29.png"),
        alt: "Atom Investor mobile fund issue form in Persian with fund selection, NAV date, investment amount, and unit estimate",
        label: "Fund issue",
        description: "A focused purchase step translates the investment amount into expected units while keeping fund and NAV context visible.",
        group: "Issue & payment",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: atom("Login-1.png"),
        alt: "Atom Investor desktop login page in Persian with mobile number and password fields, registration entry point, and partner branding",
        label: "Investor access",
        description: "The public entry point separates returning-investor access from the registration path and establishes the Pasargad product context.",
        group: "Access & identity",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1440,
        height: 1024,
      },
      {
        src: atom("Investo PWA-12.png"),
        alt: "Atom Investor mobile Sejam identity verification dialog in Persian with a verification-code field",
        label: "Sejam verification",
        description: "A focused verification dialog handles the regulatory identity checkpoint without taking the investor out of the product journey.",
        group: "Access & identity",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: atom("Investo PWA-13.png"),
        alt: "Atom Investor mobile success dialog confirming Sejam identity verification in Persian",
        label: "Identity confirmed",
        description: "A clear success state closes the Sejam step and sets expectations for the protected investor area that follows.",
        group: "Access & identity",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: atom("Investo PWA-35.png"),
        alt: "Atom Investor mobile payment-method screen in Persian offering account balance, bank gateway, and deposit receipt options",
        label: "Payment routing",
        description: "Alternative settlement paths are presented in one decision point, including gateway payment and receipt upload.",
        group: "Issue & payment",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: atom("Investo PWA-37.png"),
        alt: "Atom Investor mobile payment confirmation in Persian with successful status and transaction reference",
        label: "Payment confirmed",
        description: "The gateway return state confirms settlement and exposes a reference investors can use when following the order.",
        group: "Issue & payment",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: atom("Investo PWA-30.png"),
        alt: "Atom Investor mobile redemption form in Persian showing available and pending units",
        label: "Unit redemption",
        description: "Available and pending units are made explicit before the investor submits a redemption request.",
        group: "Servicing & records",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: atom("Investo PWA-6.png"),
        alt: "Atom Investor mobile issue-request detail in Persian showing status, fund, amount, units, and request date",
        label: "Order status",
        description: "A compact request detail makes fund, amount, unit count, date, and current processing status easy to verify.",
        group: "Servicing & records",
        theme: "light",
        emphasis: "supporting",
        device: "mobile",
        width: 375,
        height: 812,
      },
      {
        src: atom("Dashboard -1-12.jpg"),
        alt: "Atom Investor desktop account statement in Persian with Jalali date, fund, status, and request-type filters above an RTL table",
        label: "Account activity",
        description: "Jalali date, fund, status, and transaction filters turn the account statement into a practical audit surface.",
        group: "Servicing & records",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1440,
        height: 1024,
      },
      {
        src: atom("Dashboard -1-36.jpg"),
        alt: "Atom Investor desktop request report in Persian with status metrics and a detailed RTL orders table",
        label: "Request reporting",
        description: "Status summaries and a dense MUI Data Grid support fast scanning across issue and redemption requests.",
        group: "Servicing & records",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1440,
        height: 1024,
      },
    ],
    accent: "teal",
  },
  {
    slug: "enterprise-workspace",
    title: "Work Desk",
    eyebrow: "Multi-Window Enterprise Workspace",
    summary:
      "A browser-based operating environment that brings 30+ enterprise applications into one coherent, desktop-like workspace for operational teams.",
    challenge:
      "Modernize a fragmented operational environment so independent tools, dense workflows, and permission-sensitive data can coexist without sacrificing performance or usability at highly variable window sizes.",
    solution:
      "A typed modular shell with draggable and resizable application windows, portal-aware stacking, container-query layouts, domain-focused services, and shared workflow primitives.",
    achievements: [
      "30+ applications in one workspace shell",
      "12+ domain-scoped TypeScript modules",
      "Permission-aware meetings and task workflows",
      "Full meeting lifecycle E2E coverage",
    ],
    tech: ["Next.js", "TypeScript", "Shadcn/ui", "Playwright", "TanStack Query", "React Hook Form", "Recharts", "TanStack Table", "Tailwind CSS"],
    confidential: true,
    previewLabel: "WORK DESK / OPERATIONS OS",
    previewStatus: "RTL · MULTI-WINDOW",
    previewVariant: "workspace",
    businessOverview:
      "Work Desk gives operational teams one browser-based environment for the systems they use throughout the day. A desktop-style shell keeps dashboards, meetings, task management, work reports, notifications, organization tools, and supporting applications available without forcing users through disconnected products. Teams can schedule meetings, coordinate attendees and agendas, capture minutes and follow-up actions, manage work in table or Kanban views, monitor progress, and move between multiple open applications while retaining context.",
    technicalOverview:
      "The React and TypeScript frontend is organized as a shared workspace shell plus 12+ domain-scoped modules. A custom window manager supports dragging, resizing, focus, minimization, and taskbar restoration, while portal-aware stacking keeps menus, dialogs, and popovers attached to the correct window. Container queries let each application respond to its own dimensions rather than only the browser viewport. TanStack Query and typed services isolate server state by domain; React Hook Form structures long operational forms; and reusable data-grid, calendar, export, permission, and workflow primitives keep behavior consistent across meetings, tasks, files, work logs, and analytics. Playwright covers the meeting lifecycle from scheduling through minutes and follow-up work.",
    engineeringChallenges: [
      "Desktop behavior in a browser: coordinate drag, resize, focus, minimize, maximize, and taskbar state across many simultaneous application instances.",
      "Portal-aware stacking: keep dialogs, menus, date pickers, and other overlays visually attached to the correct window as focus and z-index change.",
      "Window-local responsiveness: use container queries so dense tables, forms, and calendars adapt to the space assigned to each app instead of the viewport alone.",
      "Cross-domain workflows: connect meetings, minutes, approvals, and resulting tasks while preserving typed boundaries between independently evolving modules.",
      "Permission-sensitive operations: expose actions and records according to organizational roles without fragmenting shared navigation and workflow components.",
    ],
    engineeringHeading: "A desktop interaction model, engineered for the web.",
    engineeringIntro:
      "Window orchestration, overlay ownership, local responsiveness, and cross-module state all have to stay predictable before the individual applications can feel simple.",
    technologyHeading: "A modular platform for dense operational workflows.",
    stackGroups: [
      { label: "Core", items: ["Next.js App Router", "React", "TypeScript", "Modular application shell"] },
      { label: "Workspace", items: ["Custom window manager", "Portal-aware stacking", "Container Queries", "Taskbar state"] },
      { label: "Data & forms", items: ["TanStack Query", "Typed services", "React Hook Form","Zod", "Domain validation"] },
      { label: "UI & RTL", items: ["Shadcn/ui", "TanStack Table", "Tailwind CSS", "Recharts"] },
      { label: "Operations", items: ["Kanban", "Meeting workflows", "Excel export", "Analytics reporting"] },
      { label: "Quality", items: ["Playwright", "Lifecycle E2E coverage", "Permission scenarios"] },
    ],
    gallery: {
      eyebrow: "Workspace walkthrough",
      title: "Many operational systems. One continuous workspace.",
      intro:
        "The selected screens show the platform at three levels: the multi-window shell that preserves context, complete meeting-to-action workflows, and dense task surfaces that support both execution and reporting.",
      capabilities: ["Multi-window shell", "Meetings", "Minutes", "Follow-up actions", "Task grids", "Kanban", "Reporting"],
      groups: [
        { name: "Workspace orchestration", description: "Independent applications remain movable, resizable, theme-aware, and accessible from a persistent shell and taskbar." },
        { name: "Meeting lifecycle", description: "Scheduling, participants, agendas, minutes, attendance, agreements, and follow-up actions stay connected from one meeting record." },
        { name: "Task execution", description: "Creation, ownership, priority, progress, approval, and status are available through focused forms, dense grids, and Kanban lanes." },
        { name: "Operational reporting", description: "Filters, summaries, timelines, export, and capacity views turn daily work into an inspectable management surface." },
      ],
    },
    images: [
      {
        src: workDesk("Screenshot 2026-07-29 090511.png"),
        alt: "Work Desk Persian RTL desktop with meeting registration, calendar, clock, notes, team metrics, chart, sidebar, and application taskbar",
        label: "Multi-window workspace",
        description: "Resizable applications share a persistent desktop, navigation rail, and taskbar while each panel preserves its own responsive layout.",
        group: "Workspace orchestration",
        theme: "light",
        emphasis: "hero",
        device: "desktop",
        width: 1913,
        height: 909,
      },
      {
        src: workDesk("Screenshot 2026-07-29 090400.png"),
        alt: "Work Desk dark-theme Persian RTL desktop with task creation, calendar, clock, notes, team metrics, and progress chart",
        label: "Theme-aware desktop",
        description: "The complete workspace and its hosted applications retain hierarchy and contrast in a coordinated dark theme.",
        group: "Workspace orchestration",
        theme: "dark",
        emphasis: "feature",
        device: "desktop",
        width: 1915,
        height: 903,
      },
      {
        src: workDesk("Screenshot 2026-07-28 200909.png"),
        alt: "Work Desk Persian RTL desktop with meeting form, calendar, agenda list, notes, and multiple simultaneous application windows",
        label: "Context-preserving windows",
        description: "Related tools can remain open together, reducing navigation loss across scheduling, reference, and note-taking tasks.",
        group: "Workspace orchestration",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1914,
        height: 907,
      },
      {
        src: workDesk("Screenshot 2026-07-28 165612.png"),
        alt: "Work Desk Persian RTL meeting details and archive windows with participants, attendees, agenda items, and record actions",
        label: "Meeting coordination",
        description: "Participant roles, attendees, location, timing, agenda, and archive actions stay visible across linked meeting windows.",
        group: "Meeting lifecycle",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1909,
        height: 910,
      },
      {
        src: workDesk("Screenshot 2026-08-06 170447.png"),
        alt: "Work Desk Persian RTL meeting-minutes editor with agenda navigation, agreement text, follow-up action fields, preview, and final submission",
        label: "Minutes & agreements",
        description: "Agenda-led minutes connect agreements to responsible owners and deadlines before review and final submission.",
        group: "Meeting lifecycle",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1913,
        height: 906,
      },
      {
        src: workDesk("Screenshot 2026-08-06 170936.png"),
        alt: "Work Desk Persian RTL meeting attendance form beside task creation with owners, approvers, and informed participants",
        label: "Meeting-to-task handoff",
        description: "Attendance outcomes and meeting decisions can move directly into owned, approved, and observable follow-up work.",
        group: "Meeting lifecycle",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1914,
        height: 913,
      },
      {
        src: workDesk("Screenshot 2026-08-06 170109.png"),
        alt: "Work Desk Persian RTL task creation window with title, description, priority, dates, progress calculation, labels, owners, approvers, and observers",
        label: "Structured task creation",
        description: "A large adaptive form keeps scheduling, priority, ownership, approval, and visibility rules understandable in one task definition.",
        group: "Task execution",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1913,
        height: 910,
      },
      {
        src: workDesk("Screenshot 2026-07-28 194805.png"),
        alt: "Work Desk Persian RTL Kanban board with new, in-progress, awaiting-approval, revision, completed, and canceled task lanes",
        label: "Permission-aware Kanban",
        description: "Lifecycle lanes make current work and approval states scannable while retaining role and priority filters.",
        group: "Task execution",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1864,
        height: 901,
      },
      {
        src: workDesk("Screenshot 2026-07-29 120208.png"),
        alt: "Work Desk Persian RTL task-management grid with search, configurable columns, statuses, priorities, progress, deadlines, and row actions",
        label: "Operational task grid",
        description: "A dense configurable table supports scanning, filtering, and acting across ownership, progress, approval, and timing data.",
        group: "Task execution",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1908,
        height: 908,
      },
      {
        src: workDesk("Screenshot 2026-07-28 200052.png"),
        alt: "Work Desk Persian RTL work-monitoring report with date and employee filters, status summaries, progress metrics, export, and detailed task table",
        label: "Work monitoring report",
        description: "Date and team filters, status summaries, progress indicators, and Excel export turn execution data into an auditable report.",
        group: "Operational reporting",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1702,
        height: 845,
      },
    ],
    accent: "teal",
  },
  {
    slug: "sms-platform",
    title: "SMS Sender",
    eyebrow: "Messaging · Campaign management",
    summary:
      "Role-based console for capital-market SMS, event templates, composing, scheduling, approving, and tracking targeted messages.",
    challenge:
      "Replace ad-hoc messaging with a controlled operational workflow that serves admins, support teams, and brokers while keeping market communications targeted, reviewable, and traceable.",
    solution:
      "A role-aware React console that unifies recipient sources, Jalali scheduling, parameterized templates, drafts, approvals, interest rules, archives, reporting, and Excel workflows.",
    achievements: [
      "Manual, Excel, and phonebook recipient flows",
      "Parameterized market-event campaigns",
      "Role-gated drafts and approval queues",
      "Auditable archives, logs, and reports",
    ],
    tech: ["React", "Redux Toolkit", "React Query", "Material UI", "React Hook Form", "CoreUI", "Axios", "Jest"],
    previewLabel: "SMS SENDER / MARKET NOTIFIER UI",
    previewStatus: "RTL · ROLE-BASED",
    previewVariant: "messaging",
    businessOverview:
      "SMS Sender helps capital-market operations teams notify customers about market events, instrument stops, and custom campaigns without relying on ad-hoc messaging tools. Users compose SMS from manual numbers, Excel uploads, or an in-app phonebook, then send immediately or on Jalali-based schedules. Brokers and admins define market-event and stop-instrument campaigns with parameterized templates, keep unfinished work as drafts, and review pending requests before they go live. Contact teams manage customer lists and white/black-list interests so messages reach the right audience. Archives, system event logs, and date-range statistical reports provide visibility into what was sent and when, while role-based navigation keeps each user focused on permitted workflows.",
    technicalOverview:
      "The product uses React with HashRouter and lazy-loaded routes, a CoreUI application shell, and Material UI for dense forms, dialogs, and tables. Emotion provides the RTL style cache, while Redux Toolkit coordinates roles, drafts, pending-request badges, sidebar behavior, and selected market-event context. Fetch, Axios, and React Query support data access; React Hook Form structures validation-heavy workflows; and Jalali date tools, Excel export libraries, and a custom TypeScript formula DSL support scheduling, reporting, template rules, and customer-interest settings.",
    engineeringChallenges: [
      "Formula settings: tokenize, parse, and serialize an AST so volume, value, and timing rules remain editable while staying compatible with API contracts.",
      "Role gating: translate permission subjects into Redux roles, route allowlists, role-specific navigation, and live operational badges.",
      "Multi-mode SMS: normalize manual, Excel, and phonebook recipients plus Jalali scheduling modes into one predictable send flow.",
      "RTL data grids: reuse sorting, pagination, loading skeletons, date filters, and Excel export patterns across archives and reports.",
      "Queue visibility: refresh draft and pending-request counts on application boot and tab focus so sidebar badges remain trustworthy.",
    ],
    engineeringHeading: "Operational complexity resolved before send.",
    engineeringIntro:
      "Recipient normalization, formula parsing, permission boundaries, and queue synchronization protect the workflows behind a deceptively simple message action.",
    technologyHeading: "Built for dense, permission-aware RTL operations.",
    stackGroups: [
      { label: "Core", items: ["React", "React Router", "HashRouter", "Lazy-loaded routes"] },
      { label: "State", items: ["Redux Toolkit", "React Redux", "React Query"] },
      { label: "Data & forms", items: ["Fetch", "Axios", "React Hook Form", "Custom validation", "react-number-format"] },
      { label: "UI & RTL", items: ["Material UI", "CoreUI", "Emotion", "stylis-plugin-rtl", "Sass"] },
      { label: "Dates & tables", items: ["MUI Table", "Pagination", "Skeleton", "react-multi-date-picker", "jalali-moment"] },
      { label: "Export & quality", items: ["sheetjs-style", "xlsx", "file-saver", "Jest", "Docker", "Nginx"] },
    ],
    gallery: {
      eyebrow: "Operations walkthrough",
      title: "From market signal to governed communication.",
      intro:
        "The selected screens prioritize operational breadth and credibility: composing across recipient sources, managing market-event records, editing parameterized templates, reviewing requests, and targeting customers through explicit interest rules.",
      capabilities: ["Multi-mode send", "Jalali scheduling", "Event templates", "Draft queues", "Approvals", "Audience rules", "Reporting"],
      groups: [
        { name: "Campaign delivery", description: "A single composition surface normalizes recipient entry and scheduled delivery without hiding operational constraints." },
        { name: "Market operations", description: "Event archives and reusable templates connect market context, instrument data, timing, and message content." },
        { name: "Governance & visibility", description: "Status-rich queues make broker requests, review ownership, and approval outcomes easy to audit." },
        { name: "Audience management", description: "Customer, instrument, and event interests create explicit targeting rules instead of relying on disconnected contact files." },
      ],
    },
    images: [
      {
        src: sms("17500582_xxl-1.png"),
        alt: "SMS Sender Persian RTL message composer with text entry, manual, Excel, and phonebook recipient modes, scheduling controls, and role-based navigation",
        label: "Multi-mode SMS composer",
        description: "Manual entry, Excel import, and phonebook recipients converge in one send flow with immediate and Jalali-scheduled delivery.",
        group: "Campaign delivery",
        theme: "light",
        emphasis: "hero",
        device: "desktop",
        width: 1600,
        height: 805,
      },
      {
        src: sms("17500586_xxl-1.png"),
        alt: "SMS Sender Persian RTL market-event archive with filters, Excel export, status badges, pagination, and a populated event table",
        label: "Market-event archive",
        description: "Search, export, status, and date controls keep thousands of instrument-linked event communications traceable.",
        group: "Market operations",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1600,
        height: 805,
      },
      {
        src: sms("17544170_xxl-1.png"),
        alt: "SMS Sender Persian RTL template editor dialog with delivery time, volume and value rules, message body, and an open event-parameter selector",
        label: "Parameterized templates",
        description: "Operators combine editable message copy with event fields, minimum thresholds, expiry, and daily delivery timing.",
        group: "Market operations",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1600,
        height: 833,
      },
      {
        src: sms("Screenshot (186).png"),
        alt: "SMS Sender Persian RTL approval-request queue showing requester, approver, request details, status badges, and review timestamps",
        label: "Approval queue",
        description: "Suspended broker requests expose ownership, timing, campaign detail, and approval state in a compact review surface.",
        group: "Governance & visibility",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1343,
        height: 649,
      },
      {
        src: sms("17544198_xxl-1.png"),
        alt: "SMS Sender Persian RTL customer-interest editor linking selected contacts, market instruments, and notification events",
        label: "Customer interest editor",
        description: "Contact, instrument, and event selections make audience targeting explicit and editable before campaigns are sent.",
        group: "Audience management",
        theme: "light",
        emphasis: "feature",
        device: "desktop",
        width: 1600,
        height: 803,
      },
      {
        src: sms("Screenshot (244).png"),
        alt: "SMS Sender Persian RTL grouped interest-list settings with customers expanded into instrument and event rules",
        label: "Interest-rule overview",
        description: "Expandable customer groups reveal detailed instrument and event subscriptions, including excluded rules and editable list states.",
        group: "Audience management",
        theme: "light",
        emphasis: "supporting",
        device: "desktop",
        width: 1872,
        height: 960,
      },
    ],
    accent: "coral",
  },
];

export const projects = [
  projectCatalog[3],
  projectCatalog[1],
  projectCatalog[2],
  projectCatalog[0],
  projectCatalog[4],
];

export const skillGroups = [
  {
    title: "Frontend systems",
    description: "Scalable, typed interfaces built around clear domain boundaries.",
    skills: ["React", "Next.js", "TypeScript", "JavaScript ES6+", "Vue.js", "Tailwind CSS"],
  },
  {
    title: "Architecture & data",
    description: "Reliable client architecture for dense, real-time products.",
    skills: ["React Query", "Redux", "Redux Saga", "REST APIs", "Axios", "SSE", "Zod"],
  },
  {
    title: "Product & UI engineering",
    description: "Accessible design systems and workflows for expert users.",
    skills: ["Figma", "Material UI", "shadcn/ui", "Sass", "Responsive UI", "Adobe Photoshop"],
  },
  {
    title: "Quality & delivery",
    description: "Testing and team practices that make change safer.",
    skills: ["Playwright", "Cypress", "Git", "GitHub", "Scrum", "Cross-browser delivery"],
  },
];

export const technologies = [
  "React",
  "Next.js",
  "TypeScript",
  "React Query",
  "Redux",
  "Playwright",
  "Tailwind CSS",
  "Material UI",
  "React Hook Form",
  "Zod",
  "PostgreSQL",
  "Microsoft SQL Server",
  "Figma",
  "Git",
];

export const education = {
  degree: "B.Sc. Software Engineering",
  school: "Bu-Ali Sina University",
  location: "Hamedan",
  period: "2016 — 2020",
};

export const languages = [
  { name: "Persian", level: "Native" },
  { name: "English", level: "Professional working proficiency" },
];

export const interests = ["Product design", "Games", "Cinema"];
